INSERT INTO tutorials (name, description, level) VALUES ('Sitting', ARRAY ['Hold a treat in your hand. Put a treat into your hand and move it in front of your dog or puppy''s mouth and nose until you get their attention. Let them sniff and nibble.', 'Move the treat above the dog''s head and say the word sit. Once your dog is focused, slowly move the treat up and slightly behind their head. (Aim for about three inches above them.) This should cause your puppy to move backward before eventually sitting.', 'Once in a sit, praise your dog! As soon as your dog''s bottom touches the floor, happily say Good sit! and then reward your dog with a treat to let them know that this was the correct behavior. By saying good sit, your dog will continue to hear the word sit and better associate it with the action that just happened.', 'Repeat this process. You should do about 10 to 15 repetitions of this in a calm and comfortable area where your dog can focus and learn. Count out your dog training treats beforehand so you can keep track of how many repetitions you have done.'], 'easy');

INSERT INTO tutorials (name, description, level) VALUES ('Sing', ARRAY ['Sing yourself. Choose a song and sing it, not necessarily well, all the time. When you are cooking, cleaning, during the commercials on TV, just look at your puppy and sing. Throw some barks and howls in there too.', 'If your dog does bark or howl while you are singing, then TREAT instantly. Praise them for doing so well. Just don''t punish them for not singing. Honestly, if I were a dog, I don''t'' know what I''d have thought about me when I would sing to Pierre.', 'If it doesn''t work, keep trying. Play some videos from the internet loud enough for your dog to hear. Just keep trying. Sing more. Howl more. Turn into a dog yourself (kidding. I don''t think that will work).'], 'expert');
INSERT INTO tutorials (name, description, level) VALUES ('Bark', ARRAY ['Use positive reinforcement. If you want to train your dog to bark in response to a speak command or hand signal, you''ll have to reward barking occasionally. Having a dog treat ready will make it easier to quickly show your barking dog that only certain kinds of barking—barks that are in response to a specific stimulus—will be rewarded.', 'Teach the quiet command. Before you encourage your dog''s barking, you should teach them a quiet command. To do this, you''ll need a bottle filled with coins and some dog treats. When your dog barks excessively, say quiet, shake the penny bottle and say quiet again. As the days go by, shake the bottle less and less and rely more on the verbal command. When your dog stops barking, treat them. Keep several penny bottles around the house in key areas where excessive barking is common—near the front door, kitchen, couch, etc. Teaching your dog how to stop barking will make your training sessions easier to manage.', 'Encourage your dog to bark. A vocal dog will be easier to train to bark on cue. If you have a quieter dog, prompt them to bark by getting them excited with a favorite toy or by having someone else in your household ring the doorbell.', 'Mark the bark. Once your dog barks, mark the behavior with a vocal command like speak. Then, give your dog a tasty treat (or click, if you are using clicker training) to reinforce the command. As you move forward with your training, be sure to mark a single bark at a time so your dog does not get the impression that you are rewarding them for barking wildly.', 'Add a hand signal. Next, add a hand gesture to reinforce the vocal command. When your dog barks, say speak and use a hand signal (for instance, opening and closing your fist while holding it in front of your face.) Continue using the verbal cue with the hand gesture for the remainder of your training sessions. Your dog will eventually learn that the gesture and the verbal cue represent the speak command.'], 'easy');

INSERT INTO tutorials (name, description, level) VALUES ('Give A Pow', ARRAY ['When your dog is in a sit position, tickle the back of one of your dog''s front feet (choose the same leg to begin with!). As soon as she moves her foot then give her a treat.', 'As she starts to predict you tickling her foot then just hold your hand a little further away so she starts to lift her paw herself. As soon as she does this then give her a treat.', 'Now start to hold your hand a little higher so she learns to lift her paw to meet your hand.'], 'easy');

INSERT INTO tutorials (name, description, level) VALUES ('Come', ARRAY ['Start in a safe, quiet spot. Find an area with minimal distractions to begin training. This could be your backyard or somewhere in your home. Allow your dog to wander and explore.', 'Say your dog''s name, then tell them to come to you. After about five minutes, say your dog''s name and then give your dog the come command (literally say the word come).  As they start moving toward you, encourage your dog by cheering them on. You can even praise your dog for looking in your direction after saying come in these early stages of training. (FYI, in the dog training world, command and cue are interchangeable words.', 'Give your dog a treat. Reward your dog with tasty training treats once they approach you and make sure to give them some happy scratches, pats and rubs. This helps them know they did a good job. You could also surprise them with their favorite toy!', 'Repeat several more times. Let your puppy go back to exploring some more, and then repeat Steps 1-3. Aim for 15- to 20-minute training sessions and repeat every day or two so that it becomes better ingrained in their head. With consistent training sessions, you can expect your dog to reliably come when called within one to two months. Some dogs might take longer or shorter to achieve a reliable recall.'], 'easy');
INSERT INTO tutorials (name, description, level) VALUES ('Lie Down', ARRAY ['With your puppy in a sitting position, hold a treat to their nose.','Bring the treat down between your puppy''s front paws. They should lower their head to follow the treat.','Continue moving the treat out along the ground away from your puppy. You are essentially making an L shape. As your puppy follows the treat, they should lie down.','As soon as your puppy is in the down position, click and praise then immediately give them the lure as their reward.','After several repetitions, begin to use a treat from your other hand as a reward so the lure no longer gets eaten.','Finally, lure your puppy with an empty hand and reward with a treat from the opposite hand. Now you''ve taught a hand signal which is lowering your hand towards the ground.','Once your puppy is responding to the hand signal you can teach a verbal cue by saying Down a second before you give the hand signal. In time, your puppy should respond to the verbal cue alone.'], 'medium');
INSERT INTO tutorials (name, description, level) VALUES ('', ARRAY [], '', '', '');

-- INSERT INTO tutorials (id, description, timestamp, video_path) VALUES (1, 'Trying to sit, being stubborn.', NOW()::timestamp, 'https://www.kapwing.com/e/62393b57313570006d1eff18');

-- INSERT INTO tutorials (id, description, timestamp, video_path) VALUES (2, 'Bailey is a beautiful singer.', NOW()::timestamp, 'https://www.kapwing.com/e/623942171c877700c4a93070');
-- INSERT INTO tutorials (id, description, timestamp, video_path) VALUES (3, 'Have you seen Squid Game?', NOW()::timestamp, 'https://www.kapwing.com/e/6239432f2d096200f105ca0b');

-- https://www.kapwing.com/e/6239432f2d096200f105ca0b