DROP TABLE IF EXISTS skills CASCADE;
CREATE TABLE skills (
  id SERIAL PRIMARY KEY NOT NULL,
  dog_id INTEGER REFERENCES dogs(id) ON DELETE CASCADE,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255) NOT NULL
);
